from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from specflow.templates.profiles import DEFAULT_TEMPLATE_SLUG


@dataclass(frozen=True)
class TemplateAsset:
    """A reusable template snippet exposed through MCP template tools."""

    key: str
    category: str
    title: str
    description: str
    tags: tuple[str, ...]
    content: str

    def to_metadata(self) -> dict[str, Any]:
        return {
            "key": self.key,
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "tags": list(self.tags),
        }


TEMPLATE_ASSETS: tuple[TemplateAsset, ...] = (
    TemplateAsset(
        key="api/tickets_router.py",
        category="api",
        title="Ticket API Router",
        description="FastAPI router template for listing and creating tickets.",
        tags=("ticket-system", "fastapi", "crud", "api"),
        content="""from fastapi import APIRouter

router = APIRouter(prefix="/tickets", tags=["tickets"])


@router.get("/")
def list_tickets() -> dict[str, list[dict[str, str]]]:
    return {"items": []}


@router.post("/")
def create_ticket() -> dict[str, str]:
    return {"status": "created"}
""",
    ),
    TemplateAsset(
        key="pages/ticket-list.tsx",
        category="page",
        title="Ticket List Page",
        description="React page template for rendering ticket list data.",
        tags=("ticket-system", "react", "vite", "page", "list"),
        content="""export function TicketListPage() {
  return (
    <section>
      <h1>Tickets</h1>
      <p>Open tickets will appear here.</p>
    </section>
  );
}
""",
    ),
    TemplateAsset(
        key="pages/ticket-detail.tsx",
        category="page",
        title="Ticket Detail Page",
        description="React page template for viewing a single ticket.",
        tags=("ticket-system", "react", "detail", "page"),
        content="""export function TicketDetailPage() {
  return (
    <section>
      <h1>Ticket Detail</h1>
      <p>Selected ticket metadata and comments.</p>
    </section>
  );
}
""",
    ),
    TemplateAsset(
        key="tests/test_ticket_api.py",
        category="test",
        title="Ticket API Test",
        description="Pytest template for validating the ticket API router.",
        tags=("ticket-system", "pytest", "api", "test"),
        content="""def test_list_tickets_returns_items(client):
    response = client.get("/tickets/")
    assert response.status_code == 200
""",
    ),
    TemplateAsset(
        key="config/playwright.config.ts",
        category="config",
        title="Playwright Config",
        description="Starter Playwright config for the generated frontend app.",
        tags=("ticket-system", "playwright", "frontend", "config"),
        content="""import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  use: {
    baseURL: "http://localhost:5173",
  },
});
""",
    ),
)


PROJECT_SCAFFOLD_FILES: dict[str, dict[str, str]] = {
    DEFAULT_TEMPLATE_SLUG: {
        "README.md": """# Ticket System

Generated by SpecFlow-Agent.
""",
        ".gitignore": """node_modules/
dist/
.pytest_cache/
__pycache__/
*.pyc
""",
        "backend/pyproject.toml": """[project]
name = "ticket-system-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["fastapi", "uvicorn"]
""",
        "backend/app/main.py": """from fastapi import FastAPI

from app.api.tickets import router as tickets_router

app = FastAPI(title="Ticket System Backend")
app.include_router(tickets_router)


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok"}
""",
        "backend/app/api/__init__.py": "",
        "backend/app/api/tickets.py": """from fastapi import APIRouter

router = APIRouter(prefix="/tickets", tags=["tickets"])


@router.get("/")
def list_tickets() -> dict[str, list[dict[str, str]]]:
    return {"items": []}
""",
        "backend/tests/test_health.py": """from app.main import app
from fastapi.testclient import TestClient

client = TestClient(app)


def test_healthz() -> None:
    response = client.get("/healthz")
    assert response.status_code == 200
""",
        "frontend/package.json": """{
  "name": "ticket-system-frontend",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "vite",
    "build": "echo build",
    "lint": "echo lint",
    "typecheck": "echo typecheck",
    "test": "echo test"
  }
}
""",
        "frontend/index.html": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ticket System</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
""",
        "frontend/src/main.tsx": """import React from "react";
import ReactDOM from "react-dom/client";

import { App } from "./App";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
""",
        "frontend/src/App.tsx": """export function App() {
  return (
    <main>
      <h1>Ticket Dashboard</h1>
      <p>Generated starter app.</p>
    </main>
  );
}
""",
    }
}


class TemplateLibrary:
    """In-memory template catalog for Sprint 3 MCP tools."""

    def __init__(self, assets: tuple[TemplateAsset, ...] = TEMPLATE_ASSETS) -> None:
        self._assets = assets
        self._asset_map = {asset.key: asset for asset in assets}

    def list_templates(self) -> list[dict[str, Any]]:
        return [asset.to_metadata() for asset in self._assets]

    def get_template(self, key: str) -> TemplateAsset:
        try:
            return self._asset_map[key]
        except KeyError as exc:
            raise KeyError(f"Unknown template key: {key}") from exc

    def search_templates(
        self,
        query: str | None = None,
        *,
        category: str | None = None,
    ) -> list[dict[str, Any]]:
        normalized = (query or "").strip().lower()
        tokens = [token for token in normalized.split() if token]
        results: list[tuple[int, TemplateAsset]] = []
        for asset in self._assets:
            if category is not None and asset.category != category:
                continue
            title = asset.title.lower()
            description = asset.description.lower()
            key = asset.key.lower()
            tags = " ".join(asset.tags).lower()
            content = asset.content.lower()
            haystack = " ".join([key, title, description, tags, content])
            if (
                normalized
                and normalized not in haystack
                and any(token not in haystack for token in tokens)
            ):
                continue
            score = 0
            if normalized:
                score += 30 if normalized in title else 0
                score += 20 if normalized in description else 0
                score += 15 if normalized in key else 0
                score += 10 if normalized in tags else 0
            for token in tokens:
                score += 8 if token in title else 0
                score += 5 if token in description else 0
                score += 20 if token in asset.category.lower() else 0
                score += 4 if token in key else 0
                score += 2 if token in tags else 0
            results.append((score, asset))
        results.sort(key=lambda item: (-item[0], item[1].key))
        return [asset.to_metadata() for _, asset in results]

    def get_project_scaffold(self, template_slug: str = DEFAULT_TEMPLATE_SLUG) -> dict[str, str]:
        try:
            return dict(PROJECT_SCAFFOLD_FILES[template_slug])
        except KeyError as exc:
            raise KeyError(f"Unknown project scaffold template: {template_slug}") from exc


def get_default_template_library() -> TemplateLibrary:
    return TemplateLibrary()
