from __future__ import annotations

from textwrap import dedent


def build_workspace_files(
    *,
    ticket_api_template: str,
    ticket_list_template: str,
    ticket_detail_template: str,
    ticket_test_template: str,
    playwright_config_template: str,
    spec_excerpt: str,
    tasks_excerpt: str,
) -> dict[str, str]:
    """Return the deterministic Sprint 5 workspace blueprint."""

    router_banner = next(
        (line.strip() for line in ticket_api_template.splitlines() if line.strip()),
        "from fastapi import APIRouter",
    )
    test_banner = next(
        (line.strip() for line in ticket_test_template.splitlines() if line.strip()),
        "def test_list_tickets_returns_items(client):",
    )

    files = {
        "README.md": _clean(
            f"""
            # Simplified Internal Ticket System

            This workspace was generated by SpecFlow-Agent Sprint 5.

            ## Scope
            - Backend: FastAPI API for tickets, users, departments,
              comments, attachments, and dashboard summary.
            - Frontend: React + Vite starter pages for list, detail,
              create, edit, and dashboard flows.
            - Quality gates: backend lint, backend build, backend tests,
              backend import smoke, and frontend file validation.

            ## Frozen Spec Snapshot
            {spec_excerpt}

            ## Task Snapshot
            {tasks_excerpt}

            ## Workspace Layout
            - `backend/`: FastAPI application, tests, and migration placeholder.
            - `frontend/`: React application shell, pages, services, and types.

            ## Run Commands
            - Backend tests: `pytest backend/tests -q`
            - Backend lint: `ruff check backend/app backend/tests`
            - Backend build smoke: `python -m compileall backend`
            """
        ),
        "backend/main.py": _clean(
            """
            from app.main import app

            __all__ = ["app"]
            """
        ),
        "backend/requirements.txt": _clean(
            """
            fastapi
            uvicorn
            pydantic
            pytest
            """
        ),
        "backend/alembic/README.md": _clean(
            """
            # Alembic Placeholder

            Sprint 5 keeps migrations lightweight.
            Real migration scripts land in the implementation sprint.
            """
        ),
        "backend/app/__init__.py": _clean(
            """
            # Backend application package.
            """
        ),
        "backend/app/models/__init__.py": _clean(
            """
            from app.models.ticket import (
                AttachmentRecord,
                CommentRecord,
                DepartmentRecord,
                TicketRecord,
                TicketState,
                UserRecord,
                UserRole,
            )

            __all__ = [
                "AttachmentRecord",
                "CommentRecord",
                "DepartmentRecord",
                "TicketRecord",
                "TicketState",
                "UserRecord",
                "UserRole",
            ]
            """
        ),
        "backend/app/models/ticket.py": _clean(
            """
            from __future__ import annotations

            from enum import StrEnum

            from pydantic import BaseModel, Field


            class TicketState(StrEnum):
                OPEN = "open"
                IN_PROGRESS = "in_progress"
                RESOLVED = "resolved"
                CLOSED = "closed"


            class UserRole(StrEnum):
                REQUESTER = "requester"
                ASSIGNEE = "assignee"
                ADMIN = "admin"


            class DepartmentRecord(BaseModel):
                id: str
                name: str
                code: str
                manager_id: str | None = None


            class UserRecord(BaseModel):
                id: str
                name: str
                email: str
                role: UserRole
                department_id: str | None = None


            class CommentRecord(BaseModel):
                id: str
                ticket_id: str
                author_id: str
                body: str
                is_internal: bool = False
                created_at: str


            class AttachmentRecord(BaseModel):
                id: str
                ticket_id: str
                comment_id: str | None = None
                file_name: str
                content_type: str
                storage_path: str
                uploaded_by: str


            class TicketRecord(BaseModel):
                id: str
                title: str
                description: str
                state: TicketState = TicketState.OPEN
                priority: str = "P3"
                requester_id: str
                assignee_id: str | None = None
                department_id: str
                comments: list[CommentRecord] = Field(default_factory=list)
                attachments: list[AttachmentRecord] = Field(default_factory=list)
            """
        ),
        "backend/app/schemas/__init__.py": _clean(
            """
            from app.schemas.ticket import (
                AttachmentCreateRequest,
                CommentCreateRequest,
                DashboardSummary,
                TicketCreateRequest,
                TicketListResponse,
                TicketTransitionRequest,
                TicketUpdateRequest,
            )

            __all__ = [
                "AttachmentCreateRequest",
                "CommentCreateRequest",
                "DashboardSummary",
                "TicketCreateRequest",
                "TicketListResponse",
                "TicketTransitionRequest",
                "TicketUpdateRequest",
            ]
            """
        ),
        "backend/app/schemas/ticket.py": _clean(
            """
            from __future__ import annotations

            from pydantic import BaseModel, Field

            from app.models.ticket import AttachmentRecord, CommentRecord, TicketRecord, TicketState


            class TicketCreateRequest(BaseModel):
                title: str = Field(min_length=3)
                description: str = Field(min_length=5)
                priority: str = "P3"
                requester_id: str
                department_id: str


            class TicketUpdateRequest(BaseModel):
                title: str | None = None
                description: str | None = None
                priority: str | None = None
                assignee_id: str | None = None
                department_id: str | None = None


            class TicketTransitionRequest(BaseModel):
                state: TicketState
                comment: str = Field(min_length=1)


            class CommentCreateRequest(BaseModel):
                author_id: str
                body: str = Field(min_length=1)
                is_internal: bool = False


            class AttachmentCreateRequest(BaseModel):
                uploaded_by: str
                file_name: str = Field(min_length=1)
                content_type: str = Field(min_length=1)


            class TicketListResponse(BaseModel):
                items: list[TicketRecord]
                total: int
                page: int
                page_size: int


            class DashboardSummary(BaseModel):
                open_tickets: int
                in_progress_tickets: int
                resolved_tickets: int
                closed_tickets: int
                tickets_by_department: dict[str, int]
                tickets_by_priority: dict[str, int]
                recent_comments: list[CommentRecord]
                recent_attachments: list[AttachmentRecord]
            """
        ),
        "backend/app/services/__init__.py": _clean(
            """
            from app.services.ticket_service import ticket_service

            __all__ = ["ticket_service"]
            """
        ),
        "backend/app/services/ticket_service.py": _clean(
            """
            from __future__ import annotations

            from collections import Counter
            from itertools import count

            from app.models.ticket import (
                AttachmentRecord,
                CommentRecord,
                DepartmentRecord,
                TicketRecord,
                TicketState,
                UserRecord,
                UserRole,
            )
            from app.schemas.ticket import (
                AttachmentCreateRequest,
                CommentCreateRequest,
                DashboardSummary,
                TicketCreateRequest,
                TicketListResponse,
                TicketTransitionRequest,
                TicketUpdateRequest,
            )


            class TicketService:
                def __init__(self) -> None:
                    self._ticket_counter = count(2)
                    self._comment_counter = count(2)
                    self._attachment_counter = count(2)
                    self._departments = {
                        "dept-it": DepartmentRecord(
                            id="dept-it",
                            name="IT Support",
                            code="IT",
                            manager_id="user-admin",
                        ),
                        "dept-ops": DepartmentRecord(
                            id="dept-ops",
                            name="Operations",
                            code="OPS",
                            manager_id="user-agent",
                        ),
                    }
                    self._users = {
                        "user-requester": UserRecord(
                            id="user-requester",
                            name="Avery Requester",
                            email="avery@example.com",
                            role=UserRole.REQUESTER,
                            department_id="dept-it",
                        ),
                        "user-agent": UserRecord(
                            id="user-agent",
                            name="Blake Assignee",
                            email="blake@example.com",
                            role=UserRole.ASSIGNEE,
                            department_id="dept-ops",
                        ),
                        "user-admin": UserRecord(
                            id="user-admin",
                            name="Casey Admin",
                            email="casey@example.com",
                            role=UserRole.ADMIN,
                            department_id="dept-ops",
                        ),
                    }
                    self._tickets = {
                        "TICKET-001": TicketRecord(
                            id="TICKET-001",
                            title="VPN access issue",
                            description="Requester cannot connect to the company VPN.",
                            state=TicketState.OPEN,
                            priority="P2",
                            requester_id="user-requester",
                            assignee_id="user-agent",
                            department_id="dept-it",
                            comments=[
                                CommentRecord(
                                    id="COMMENT-001",
                                    ticket_id="TICKET-001",
                                    author_id="user-requester",
                                    body="VPN failed after password reset.",
                                    is_internal=False,
                                    created_at="2026-03-24T09:00:00Z",
                                )
                            ],
                            attachments=[
                                AttachmentRecord(
                                    id="ATTACHMENT-001",
                                    ticket_id="TICKET-001",
                                    comment_id="COMMENT-001",
                                    file_name="vpn-error.png",
                                    content_type="image/png",
                                    storage_path="attachments/vpn-error.png",
                                    uploaded_by="user-requester",
                                )
                            ],
                        )
                    }

                def list_tickets(
                    self,
                    *,
                    page: int = 1,
                    page_size: int = 20,
                    keyword: str | None = None,
                    state: TicketState | None = None,
                    priority: str | None = None,
                    department_id: str | None = None,
                ) -> TicketListResponse:
                    items = [ticket.model_copy(deep=True) for ticket in self._tickets.values()]
                    if keyword:
                        normalized = keyword.lower()
                        items = [
                            ticket
                            for ticket in items
                            if normalized in ticket.title.lower()
                            or normalized in ticket.description.lower()
                        ]
                    if state is not None:
                        items = [ticket for ticket in items if ticket.state == state]
                    if priority is not None:
                        items = [ticket for ticket in items if ticket.priority == priority]
                    if department_id is not None:
                        items = [
                            ticket for ticket in items if ticket.department_id == department_id
                        ]
                    total = len(items)
                    start = max(page - 1, 0) * page_size
                    end = start + page_size
                    return TicketListResponse(
                        items=items[start:end],
                        total=total,
                        page=page,
                        page_size=page_size,
                    )

                def get_ticket(self, ticket_id: str) -> TicketRecord:
                    return self._ticket(ticket_id).model_copy(deep=True)

                def create_ticket(self, payload: TicketCreateRequest) -> TicketRecord:
                    ticket = TicketRecord(
                        id=f"TICKET-{next(self._ticket_counter):03d}",
                        title=payload.title,
                        description=payload.description,
                        state=TicketState.OPEN,
                        priority=payload.priority,
                        requester_id=payload.requester_id,
                        assignee_id="user-agent",
                        department_id=payload.department_id,
                    )
                    self._tickets[ticket.id] = ticket
                    return ticket.model_copy(deep=True)

                def update_ticket(
                    self, ticket_id: str, payload: TicketUpdateRequest
                ) -> TicketRecord:
                    ticket = self._ticket(ticket_id)
                    for key, value in payload.model_dump(exclude_none=True).items():
                        setattr(ticket, key, value)
                    return ticket.model_copy(deep=True)

                def transition_ticket(
                    self, ticket_id: str, payload: TicketTransitionRequest
                ) -> TicketRecord:
                    ticket = self._ticket(ticket_id)
                    self._validate_transition(ticket.state, payload.state)
                    ticket.state = payload.state
                    ticket.comments.append(
                        CommentRecord(
                            id=f"COMMENT-{next(self._comment_counter):03d}",
                            ticket_id=ticket.id,
                            author_id=ticket.assignee_id or "user-admin",
                            body=payload.comment,
                            is_internal=True,
                            created_at="2026-03-24T10:00:00Z",
                        )
                    )
                    return ticket.model_copy(deep=True)

                def list_comments(self, ticket_id: str) -> list[CommentRecord]:
                    return list(self._ticket(ticket_id).comments)

                def add_comment(
                    self, ticket_id: str, payload: CommentCreateRequest
                ) -> CommentRecord:
                    ticket = self._ticket(ticket_id)
                    comment = CommentRecord(
                        id=f"COMMENT-{next(self._comment_counter):03d}",
                        ticket_id=ticket.id,
                        author_id=payload.author_id,
                        body=payload.body,
                        is_internal=payload.is_internal,
                        created_at="2026-03-24T10:05:00Z",
                    )
                    ticket.comments.append(comment)
                    return comment

                def list_attachments(self, ticket_id: str) -> list[AttachmentRecord]:
                    return list(self._ticket(ticket_id).attachments)

                def add_attachment(
                    self, ticket_id: str, payload: AttachmentCreateRequest
                ) -> AttachmentRecord:
                    ticket = self._ticket(ticket_id)
                    attachment = AttachmentRecord(
                        id=f"ATTACHMENT-{next(self._attachment_counter):03d}",
                        ticket_id=ticket.id,
                        comment_id=None,
                        file_name=payload.file_name,
                        content_type=payload.content_type,
                        storage_path=f"attachments/{payload.file_name}",
                        uploaded_by=payload.uploaded_by,
                    )
                    ticket.attachments.append(attachment)
                    return attachment

                def list_users(self) -> list[UserRecord]:
                    return list(self._users.values())

                def list_departments(self) -> list[DepartmentRecord]:
                    return list(self._departments.values())

                def dashboard_summary(self) -> DashboardSummary:
                    tickets = list(self._tickets.values())
                    by_state = Counter(ticket.state.value for ticket in tickets)
                    by_department = Counter(ticket.department_id for ticket in tickets)
                    by_priority = Counter(ticket.priority for ticket in tickets)
                    comments = [
                        comment
                        for ticket in tickets
                        for comment in ticket.comments
                    ]
                    attachments = [
                        attachment
                        for ticket in tickets
                        for attachment in ticket.attachments
                    ]
                    return DashboardSummary(
                        open_tickets=by_state.get(TicketState.OPEN.value, 0),
                        in_progress_tickets=by_state.get(TicketState.IN_PROGRESS.value, 0),
                        resolved_tickets=by_state.get(TicketState.RESOLVED.value, 0),
                        closed_tickets=by_state.get(TicketState.CLOSED.value, 0),
                        tickets_by_department=dict(by_department),
                        tickets_by_priority=dict(by_priority),
                        recent_comments=comments[-5:],
                        recent_attachments=attachments[-5:],
                    )

                def _ticket(self, ticket_id: str) -> TicketRecord:
                    try:
                        return self._tickets[ticket_id]
                    except KeyError as exc:
                        raise KeyError(f"Unknown ticket: {ticket_id}") from exc

                def _validate_transition(
                    self, current: TicketState, target: TicketState
                ) -> None:
                    allowed = {
                        TicketState.OPEN: {TicketState.IN_PROGRESS, TicketState.CLOSED},
                        TicketState.IN_PROGRESS: {
                            TicketState.RESOLVED,
                            TicketState.CLOSED,
                        },
                        TicketState.RESOLVED: {
                            TicketState.CLOSED,
                            TicketState.IN_PROGRESS,
                        },
                        TicketState.CLOSED: {TicketState.OPEN},
                    }
                    if current == target:
                        return
                    if target not in allowed[current]:
                        raise ValueError(
                            f"Invalid workflow transition: {current.value} -> {target.value}"
                        )


            ticket_service = TicketService()
            """
        ),
        "backend/app/routers/__init__.py": _clean(
            """
            from app.routers.dashboard import router as dashboard_router
            from app.routers.directories import departments_router, users_router
            from app.routers.tickets import router as tickets_router

            __all__ = [
                "dashboard_router",
                "departments_router",
                "tickets_router",
                "users_router",
            ]
            """
        ),
        "backend/app/routers/tickets.py": _clean(
            f"""
            from __future__ import annotations

            # Expanded from template snippet: {router_banner}
            from fastapi import APIRouter, HTTPException

            from app.models.ticket import TicketState
            from app.schemas.ticket import (
                AttachmentCreateRequest,
                CommentCreateRequest,
                TicketCreateRequest,
                TicketListResponse,
                TicketTransitionRequest,
                TicketUpdateRequest,
            )
            from app.services.ticket_service import ticket_service

            router = APIRouter(prefix="/api/tickets", tags=["tickets"])


            @router.get("", response_model=TicketListResponse)
            def list_tickets(
                page: int = 1,
                page_size: int = 20,
                keyword: str | None = None,
                state: str | None = None,
                priority: str | None = None,
                department_id: str | None = None,
            ) -> TicketListResponse:
                parsed_state = TicketState(state) if state else None
                return ticket_service.list_tickets(
                    page=page,
                    page_size=page_size,
                    keyword=keyword,
                    state=parsed_state,
                    priority=priority,
                    department_id=department_id,
                )


            @router.post("", status_code=201)
            def create_ticket(payload: TicketCreateRequest) -> dict[str, object]:
                ticket = ticket_service.create_ticket(payload)
                return ticket.model_dump(mode="json")


            @router.get("/{{ticket_id}}")
            def get_ticket(ticket_id: str) -> dict[str, object]:
                try:
                    ticket = ticket_service.get_ticket(ticket_id)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return ticket.model_dump(mode="json")


            @router.patch("/{{ticket_id}}")
            def update_ticket(
                ticket_id: str, payload: TicketUpdateRequest
            ) -> dict[str, object]:
                try:
                    ticket = ticket_service.update_ticket(ticket_id, payload)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return ticket.model_dump(mode="json")


            @router.post("/{{ticket_id}}/transition")
            def transition_ticket(
                ticket_id: str, payload: TicketTransitionRequest
            ) -> dict[str, object]:
                try:
                    ticket = ticket_service.transition_ticket(ticket_id, payload)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                except ValueError as exc:
                    raise HTTPException(status_code=400, detail=str(exc)) from exc
                return ticket.model_dump(mode="json")


            @router.get("/{{ticket_id}}/comments")
            def list_comments(ticket_id: str) -> dict[str, object]:
                try:
                    comments = ticket_service.list_comments(ticket_id)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return {{
                    "items": [comment.model_dump(mode="json") for comment in comments]
                }}


            @router.post("/{{ticket_id}}/comments", status_code=201)
            def add_comment(
                ticket_id: str, payload: CommentCreateRequest
            ) -> dict[str, object]:
                try:
                    comment = ticket_service.add_comment(ticket_id, payload)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return comment.model_dump(mode="json")


            @router.get("/{{ticket_id}}/attachments")
            def list_attachments(ticket_id: str) -> dict[str, object]:
                try:
                    attachments = ticket_service.list_attachments(ticket_id)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return {{
                    "items": [attachment.model_dump(mode="json") for attachment in attachments]
                }}


            @router.post("/{{ticket_id}}/attachments", status_code=201)
            def add_attachment(
                ticket_id: str, payload: AttachmentCreateRequest
            ) -> dict[str, object]:
                try:
                    attachment = ticket_service.add_attachment(ticket_id, payload)
                except KeyError as exc:
                    raise HTTPException(status_code=404, detail=str(exc)) from exc
                return attachment.model_dump(mode="json")
            """
        ),
        "backend/app/routers/directories.py": _clean(
            """
            from fastapi import APIRouter

            from app.services.ticket_service import ticket_service

            users_router = APIRouter(prefix="/api/users", tags=["users"])
            departments_router = APIRouter(prefix="/api/departments", tags=["departments"])


            @users_router.get("")
            def list_users() -> dict[str, object]:
                return {
                    "items": [
                        user.model_dump(mode="json") for user in ticket_service.list_users()
                    ]
                }


            @departments_router.get("")
            def list_departments() -> dict[str, object]:
                return {
                    "items": [
                        department.model_dump(mode="json")
                        for department in ticket_service.list_departments()
                    ]
                }
            """
        ),
        "backend/app/routers/dashboard.py": _clean(
            """
            from fastapi import APIRouter

            from app.schemas.ticket import DashboardSummary
            from app.services.ticket_service import ticket_service

            router = APIRouter(prefix="/api/dashboard", tags=["dashboard"])


            @router.get("/summary", response_model=DashboardSummary)
            def get_dashboard_summary() -> DashboardSummary:
                return ticket_service.dashboard_summary()
            """
        ),
        "backend/app/main.py": _clean(
            """
            from fastapi import FastAPI

            from app.routers.dashboard import router as dashboard_router
            from app.routers.directories import departments_router, users_router
            from app.routers.tickets import router as tickets_router

            app = FastAPI(title="Simplified Internal Ticket System Backend")
            app.include_router(tickets_router)
            app.include_router(users_router)
            app.include_router(departments_router)
            app.include_router(dashboard_router)


            @app.get("/healthz")
            def healthz() -> dict[str, str]:
                return {"status": "ok"}
            """
        ),
        "backend/tests/test_health.py": _clean(
            """
            from app.main import app
            from fastapi.testclient import TestClient

            client = TestClient(app)


            def test_healthz() -> None:
                response = client.get("/healthz")
                assert response.status_code == 200
                assert response.json() == {"status": "ok"}
            """
        ),
        "backend/tests/test_tickets.py": _clean(
            f"""
            from app.main import app
            from fastapi.testclient import TestClient

            # Seeded from template: {test_banner}

            client = TestClient(app)


            def test_ticket_list_and_directory_endpoints() -> None:
                tickets = client.get("/api/tickets", params={{"page": 1, "page_size": 20}})
                users = client.get("/api/users")
                departments = client.get("/api/departments")
                dashboard = client.get("/api/dashboard/summary")

                assert tickets.status_code == 200
                assert tickets.json()["items"]
                assert users.status_code == 200
                assert departments.status_code == 200
                assert dashboard.status_code == 200
                assert "open_tickets" in dashboard.json()


            def test_ticket_creation_update_and_transition_flow() -> None:
                created = client.post(
                    "/api/tickets",
                    json={{
                        "title": "Laptop provisioning",
                        "description": "Need a new laptop for onboarding.",
                        "priority": "P1",
                        "requester_id": "user-requester",
                        "department_id": "dept-it",
                    }},
                )
                assert created.status_code == 201
                ticket_id = created.json()["id"]

                updated = client.patch(
                    f"/api/tickets/{{ticket_id}}",
                    json={{"assignee_id": "user-agent", "priority": "P2"}},
                )
                assert updated.status_code == 200
                assert updated.json()["assignee_id"] == "user-agent"

                transitioned = client.post(
                    f"/api/tickets/{{ticket_id}}/transition",
                    json={{"state": "in_progress", "comment": "Taking ownership."}},
                )
                assert transitioned.status_code == 200
                assert transitioned.json()["state"] == "in_progress"

                comment = client.post(
                    f"/api/tickets/{{ticket_id}}/comments",
                    json={{
                        "author_id": "user-agent",
                        "body": "Provisioning has started.",
                        "is_internal": True,
                    }},
                )
                attachment = client.post(
                    f"/api/tickets/{{ticket_id}}/attachments",
                    json={{
                        "uploaded_by": "user-agent",
                        "file_name": "handoff.pdf",
                        "content_type": "application/pdf",
                    }},
                )
                detail = client.get(f"/api/tickets/{{ticket_id}}")

                assert comment.status_code == 201
                assert attachment.status_code == 201
                assert detail.status_code == 200
                assert detail.json()["attachments"]
                assert detail.json()["comments"]
            """
        ),
        "frontend/vite.config.ts": _clean(
            """
            import { defineConfig } from "vite";

            export default defineConfig({
              server: {
                port: 5173,
              },
            });
            """
        ),
        "frontend/src/types/ticket.ts": _clean(
            """
            export type TicketState = "open" | "in_progress" | "resolved" | "closed";

            export interface TicketSummary {
              id: string;
              title: string;
              description: string;
              state: TicketState;
              priority: string;
              requesterId: string;
              assigneeId?: string;
              departmentId: string;
            }
            """
        ),
        "frontend/src/services/api.ts": _clean(
            """
            export const apiRoutes = {
              tickets: "/api/tickets",
              users: "/api/users",
              departments: "/api/departments",
              dashboard: "/api/dashboard/summary",
            };
            """
        ),
        "frontend/src/components/TicketTable.tsx": _clean(
            """
            import type { TicketSummary } from "../types/ticket";

            interface TicketTableProps {
              tickets: TicketSummary[];
            }

            export function TicketTable({ tickets }: TicketTableProps) {
              return (
                <table>
                  <thead>
                    <tr>
                      <th>Ticket</th>
                      <th>State</th>
                      <th>Priority</th>
                      <th>Department</th>
                    </tr>
                  </thead>
                  <tbody>
                    {tickets.map((ticket) => (
                      <tr key={ticket.id}>
                        <td>{ticket.title}</td>
                        <td>{ticket.state}</td>
                        <td>{ticket.priority}</td>
                        <td>{ticket.departmentId}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              );
            }
            """
        ),
        "frontend/src/pages/TicketListPage.tsx": _clean(ticket_list_template),
        "frontend/src/pages/TicketDetailPage.tsx": _clean(ticket_detail_template),
        "frontend/src/pages/TicketCreatePage.tsx": _clean(
            """
            export function TicketCreatePage() {
              return (
                <section>
                  <h1>Create Ticket</h1>
                  <p>
                    Requesters can open a ticket with title, department,
                    priority, and description.
                  </p>
                </section>
              );
            }
            """
        ),
        "frontend/src/pages/TicketEditPage.tsx": _clean(
            """
            export function TicketEditPage() {
              return (
                <section>
                  <h1>Edit Ticket</h1>
                  <p>Assignees and admins can update metadata, ownership, and workflow state.</p>
                </section>
              );
            }
            """
        ),
        "frontend/src/pages/TicketDashboardPage.tsx": _clean(
            """
            export function TicketDashboardPage() {
              return (
                <section>
                  <h1>Operations Dashboard</h1>
                  <p>Queue metrics, SLA pressure, and department distribution surface here.</p>
                </section>
              );
            }
            """
        ),
        "frontend/src/App.tsx": _clean(
            """
            import { TicketTable } from "./components/TicketTable";
            import { TicketCreatePage } from "./pages/TicketCreatePage";
            import { TicketDashboardPage } from "./pages/TicketDashboardPage";
            import { TicketDetailPage } from "./pages/TicketDetailPage";
            import { TicketEditPage } from "./pages/TicketEditPage";
            import { TicketListPage } from "./pages/TicketListPage";

            const sampleTickets = [
              {
                id: "TICKET-001",
                title: "VPN access issue",
                description: "Requester cannot connect to the company VPN.",
                state: "open",
                priority: "P2",
                requesterId: "user-requester",
                assigneeId: "user-agent",
                departmentId: "dept-it",
              },
            ];

            export function App() {
              return (
                <main>
                  <TicketDashboardPage />
                  <TicketListPage />
                  <TicketTable tickets={sampleTickets} />
                  <TicketDetailPage />
                  <TicketCreatePage />
                  <TicketEditPage />
                </main>
              );
            }
            """
        ),
        "frontend/tests/dashboard.spec.ts": _clean(
            """
            test("dashboard placeholder", async () => {
              expect(true).toBeTruthy();
            });
            """
        ),
        "frontend/playwright.config.ts": _clean(playwright_config_template),
    }
    return files


def _clean(content: str) -> str:
    return dedent(content).strip() + "\n"
